<?php $this->widget('ActionInfo');?>

<?php
if((int)$dataProvider->totalItemCount===0){
?>
<div style="margin:10px 0px 0px 20px">
<?php
}else{
?>
<div style="margin:10px 0px -30px 20px">
<?php
}
?>
<button class="sexybutton sexysimple sexylarge" onclick="window.location='<?php echo Yii::app()->createUrl('product/create',array('menupanel'=>'content|product|product_create','cid'=>$_GET['cid']));?>'">添加产品</button>
<?php $this->widget('SearchForm',array('categorys'=>$categorys));?>
</div>
<?php 
	$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider'=>$dataProvider,
    'pager'=>Yii::app()->params['pager'],
    'ajaxUpdate'=>false,
    'columns'=>array(
    	array(
    		'class'=>'CCheckBoxColumn',
    		'value'=>'$data->id',
    		'htmlOptions'=>array(
    			'width'=>'5px',
    		),
    	),
    	array(
    		'name'=>'序号',
    		'value'=>'$row+1',
    		'htmlOptions'=>array(
    			'width'=>'5px',
    		),
    	),
    	'title',
    	array(
    		'name'=>'cid',
    		'value'=>'$data->category->title',
    		'htmlOptions'=>array(
    			'width'=>'80px',
    			'align'=>'center',
    		),
    	),
    	array(
    		'name'=>'bid',
    		'value'=>'$data->bcategory->title',
    		'htmlOptions'=>array(
    			'width'=>'80px',
    			'align'=>'center',
    		),
    	),
    	array(
    		'class'=>'CButtonColumn',
    		'header'=>'缩略图',
    		'buttons'=>array(
    			'preview'=>array(    
    				'url'=>'',
    				'imageUrl'=>BASEURL.'/resources/icons/picture.png',
    				'visible'=>'Yii::app()->controller->girdShowImg($data);',
    			),
    		),
    		'template'=>'{preview}',
    	),
    	array(
    		'name'=>'hits',
    		'value'=>'$data->hits',
    		'htmlOptions'=>array(
    			'width'=>'40px',
    			'align'=>'center',
    		),
    	),
    	array(
    		'name'=>'create_time',
    		'value'=>'date("Y-m-d",$data->create_time)',
    		'htmlOptions'=>array(
    			'width'=>'70px',
    			'align'=>'center',
    		),
    		'visible'=>'false',
    	),
    	array(
    		'name'=>'update_time',
    		'value'=>'date("Y-m-d",$data->update_time)',
    		'htmlOptions'=>array(
    			'width'=>'70px',
    			'align'=>'center',
    		),
    		'visible'=>'false',
    	),
    	array(
    		'class'=>'CButtonColumn',
    		'header'=>'操作',
    		'viewButtonUrl'=>'Yii::app()->controller->showViewUrl("product",$data)',
    		'viewButtonOptions'=>array('target'=>'_blank'),
    		'updateButtonUrl'=>'Yii::app()->createUrl("product/update",array("id"=>"$data->id","menupanel"=>"$_GET[menupanel]","cid"=>"$_GET[cid]","title"=>"$_GET[title]"))',
    	),
    ),
));
 ?>
