<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'Add…' => '添加本地图片',
    'AddRemote' => '添加网络图片',
    'Close' => '关闭',
    'Description' => '描述',
    'Edit information' => '修改',
    'Edit' => '编辑',
    'Name' => '名称',
    'Remove' => '删除',
    'Save changes' => '保存',
    'Select all' => '全选',
    'Drop Files Here…' => '删除文件',
    'Uploading images…' => '上传图片',
);
