
<div class="wide form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'video-form',
	'enableAjaxValidation'=>false,
	'focus'=>array($model,'title'),
	'htmlOptions'=>array('enctype'=>'multipart/form-data'),
)); ?>

	<p>以下<span class="required">*</span>为必填项.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php $this->widget('ActionInfo');?>

	
	<?php echo $form->hiddenField($model,'id',array('value'=>$model->id)); ?>
    <?php echo $form->hiddenField($model,'userid',array('value'=>Yii::app()->user->id)); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>50)); ?>
	</div>   

	<div class="row">
		<?php echo $form->labelEx($model,'cid'); ?>
		<?php echo $form->dropDownList($model,'cid',$categorys); ?>
	</div>
    
	<div class="row">
		<?php echo $form->labelEx($model,'tag'); ?>
		<?php echo $form->textField($model,'tag',array('size'=>50)); ?>
	</div> 
    
	<div class="row">
		<?php echo $form->labelEx($model,'imgurl'); ?>
	</div> 
	<div class="row">
		<?php
			$this->widget('ext.gallerymanager.GalleryManager', array(
							'gallery' => $model->galleryBehavior->getGallery(),
							'controllerRoute' => 'gallery' , //route to gallery controller
						));		
		?>
		<?php echo $form->hiddenField($model,'gallaryid'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'videourl'); ?>
		<?php echo $form->textField($model,'videourl'); ?>&nbsp;<span class="btn" onclick='showPreviewDialog();'>预览</span>
    </div>
<!--    <div class="row">
        <div style="border:1px solid #DDDDDD">
            <div class="btn-toolbar gform">
                    <span class="btn btn-success" onclick='$("#dlgVideo").dialog("open");'>
                        <i class="icon-plus icon-white"></i> 添加
                    </span>

                    <div class="btn-group">
                        <span class="btn">
                            <input type="checkbox" class="select_all" style="margin: 0;"> 全选
                         </span>
                        <span class="btn remove_selected"><i class="icon-remove"></i> 删除</span>
                    </div>
            </div>   
            <table class="table table-hover">

                <tbody>
                    <tr>
                        <td>http://www.baidu.com/test.mp4</td>
                        <td>
                            <div class="btn-group">
                                <span class="btn"><i class="icon-camera"></i>预览</span><span class="btn"><i class="icon-remove"></i> 删除</span>
                            </div>                        
                        </td>
                    </tr> 
                    <tr>
                        <td>http://www.baidu.com/test.mp4</td>
                        <td>
                            <div class="btn-group">
                                <span class="btn"><i class="icon-camera"></i>预览</span><span class="btn"><i class="icon-remove"></i> 删除</span>
                            </div>                        
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>              
	</div>    -->
	
	<div class="row">
		<?php echo $form->labelEx($model,'content'); ?>
		<?php echo $form->textArea($model,'content',array('style'=>'width:50%;height:200px')); ?>
	</div>


	<div style="width:90%;margin-left:5%">
		<fieldset>
    		<legend><strong>推荐设置</strong></legend>
    		
    		<?php 
    		if(Yii::app()->params['recommend_level']['video_display']){
    		?>
    		<div class="row">
			<?php echo $form->labelEx($model,'recommend_level'); ?>
			<?php echo $form->dropDownList($model,'recommend_level',Yii::app()->params['recommend_level']['video']); ?>
			<p class="hint">数值越大排序越靠前</p>
			</div>
			<?php }?>
    		
			<div class="row">
			</div>
  		</fieldset>
	</div>
    
	<div class="row buttons">
	<button class="sexybutton" type="submit"><span><span><span class="ok">提交</span></span></span></button>&nbsp;&nbsp;&nbsp;&nbsp;
	<button class="sexybutton" type="reset"><span><span><span class="reload">重置</span></span></span></button>
	</div>
	
<?php $this->endWidget(); ?>

</div><!-- form -->

<div id="dlgVideo" class="easyui-dialog" title="视频预览" data-options="iconCls:'icon-save',resizable:false,modal:true" style="width:550px;height:400px;padding:10px;">    
        <div style="padding:10px 0 10px 10px">  
            <?php $this->widget('application.extensions.videojs.EVideoJS', array(
                                'options' => array (
                                    // Unique identifier, is autogenerated by default, useful for jQuery integrations.
                                    'id' => false,
                                    'playerId' => 'VideoPlayer',
                                    // Video and poster width in pixels
                                    'width' => 500,
                                    // Video and poster height in pixels
                                    'height' => 300,
                                ),
                            )); 
            ?>
        </div>
</div>  

<script>
    function showPreviewDialog()
    {
        var videoPlayer = _V_("VideoPlayer");
        var videoSrc = $("#Video_videourl").val();
        if (videoSrc == '') {
            alert("请填写视频地址");
            return false;
        }
        videoPlayer.src({src: videoSrc, type: "video/mp4"});
        $("#dlgVideo").dialog("open");
        videoPlayer.play();
    }
    
    $(document).ready(function(){
       $("#dlgVideo").dialog({
          modal: true,
          closed: true,
          onBeforeClose: function () {
////              var v = $("#videoUrl").val();
////              if (v != "") {
////                  var t = $('#Video_videourl').text();
////                  t += v + "\n";
////                  $('#Video_videourl').text(t);
////                  $('#Video_videourl').show("slow");
////                  return true;
////              }
////              alert("请填写视频地址");
//              return false;
            var videoPlayer = _V_("VideoPlayer");
            videoPlayer.pause();
          }
       });
    });
</script>